name: Deploy Project
on:
  issues:
    types: [opened, edited, milestoned]
  push:
    branches:
      - 'master'
  workflow_dispatch:
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and test
        run: mvn clean verify

      - uses: actions/upload-artifact@v4
        with:
          name: spring boot app
          path: |
            ./Dockerfile
            ./target/*.jar

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: spring boot app
          path: .
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Docker build and push
        with:
          image: mhussain78/hello-flux
          tags: 0.0.2
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: notify manifest repository
        run: |
          curl -L \ 
           -X POST  https://api.github.com/repos/mhussain78/flux-bootstrap/actions/workflows/workflow_02/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"ref":"main","inputs":{"name":"Mona the Octocat","home":"San Francisco, CA"}}'