name: check the integration pipeline
on: [pull_request, push]
jobs:
  check-integration-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Running
        run: echo "Hello"

      - name: Call REST API and save in file
        run: |
               curl https://api.github.com/repos/mhussain78/fluxcd-installation-test/actions/runs -o test_runs.json

#      - name: Check on failures
#        run: exit 1