name: check the integration pipeline
on: [pull_request]
jobs:
  check-integration-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Running
        run: echo "Hello"
      - name: Check on failures
        run: exit 1