name: check the integration pipeline
on: [pull_request, push]
jobs:
  check-integration-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Running
        run: echo "Hello"

      - name: Call REST API and save in file
        run: curl https://api.github.com/repos/mhussain78/fluxcd-installation-test/actions/runs -o test_runs.json

      - name: Select the first object from json
        id: jp_output
        run: |
          first_run=$( cat test_runs.json | jq -r '[.workflow_runs[] | select(.display_title == "Kustomization/hello-flux.default")][0]' )
          echo "::set-output name=first_run::first_run"
          echo $first_run
          echo ${{ fromJson($first_run) }}



#      - name: Check on failures
#        run: exit 1